### ISSUE TITLE
USER STORY: Pre-populate the site with products

### ISSUE THREAD

**Issue by Olivertrain1221** [Olivertrain1221/CandyCave#10]
As a **Site Owner**  I will be adding all the products via a json file so that **when starting up the site it will launch with numerous products during development to help with testing**

## Tasks

- [ ] Correlate the correct category to the json file (needs to be done prior to injection to project)
- [ ] Add json file of products
- [ ] Add json file with categories listed
