### ISSUE TITLE
USER STORY: Can delete there Profile

### ISSUE THREAD

**Issue by Olivertrain1221** [Olivertrain1221/CandyCave#12]
As a **User**  I can **Delete and edit my profile** so that **If I no longer user the site or details change I can update accordingly**

## Tasks

- [ ] Basic CRUD Functionality to the profile
- [ ] Basic CRUD Functionality to Billing info
- [ ] Basic CRUD Functionality to Delivery info
