### ISSUE TITLE
USER STORY: Logout

### ISSUE THREAD

**Issue by Olivertrain1221** [Olivertrain1221/CandyCave#14]
As a **User**  I can **Logout** so that **my information is not available to anyone that uses the computer**

## Tasks

- [ ] Unable to view Current Basket
- [ ] Unable to view Past Orders
- [ ] Unable to view Delivery Information
- [ ] Unable to view Current orders
