### ISSUE TITLE
USER STORY: Logging In/Out

### ISSUE THREAD

**Issue by Olivertrain1221** [Olivertrain1221/CandyCave#8]
As a **User**  I can **login/logout** so that **I can keep all releveant information in once place to view**

## Tasks

- [ ] Can view Current Basket
- [ ] Can view Past Orders
- [ ] Can store Delivery Information
- [ ] Can store Current orders
